version: '3'
services:
  #frontend:
  #  build: ./frontend/.
  #  ports:
  #    - 5001:80
  #  environment:
  #      - NODE-ENV=production
  #  networks:
  #    - governetwork
  #  depends_on:
  #    - "backend"
  graphql:
    build: ./graphql/.
    ports: 
      - 5000:5000
    environment:
      - PGUSER=${CONNSTR}
    networks:
      - governetwork
    depends_on:
      - "database"
      - "loader"
  backend:
    build: ./backend/.
    ports:
      - 3000:3000
    environment:
      - PGUSER=${DATABASEUSER}
      - PGHOST=${DATABASEHOST}
      - PGPASSWORD=${DATABASEPASSWORD}
      - PGDATABASE=${DATABASE}
      - PGPORT=${PORT}
    networks:
      - governetwork
    depends_on:
      - "database"
      - "loader"
  database:
    build: ./database/.
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=${DATABASEPASSWORD}
    networks:
      - governetwork
  loader:
    build: ./loader/.
    ports:
      - 3001:5000
    environment:
      - DATABSEPASSWORD=${DATABASEPASSWORD}
      - DATABASEHOST=${DATABASEHOST}
      - DATABASEUSER=${DATABASEUSER}
      - DATABASE=${DATABASE}
    networks:
      - governetwork
    depends_on:
      - "database"
networks:
  governetwork:
    driver: bridge