version: '3'
services:
  postgres:
    build: ./database/.
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=example
    networks:
      - governetwork
  loader:
    build: ./loader/.
    ports:
      - 5000:5000
    environment:
      - POSTGRES_PASSWORD=example
    networks:
      - governetwork
    depends_on:
      - "postgres"
networks:
  governetwork:
    driver: bridge