version: '3'
services:
  backend:
    build: ./backend/.
    ports:
      - 8080:8080
    environment:
      - PGUSER=${PGUSER}
      - PGHOST=${PGHOST}
      - PGPASSWORD=${PGPASSWORD}
      - PGDATABASE=${PGDATABASE}
      - PGPORT=${PGPORT}
    networks:
      - governetwork
    depends_on:
      - "postgres"
      - "loader"
  postgres:
    build: ./database/.
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=${PGPASSWORD}
    networks:
      - governetwork
  loader:
    build: ./loader/.
    ports:
      - 5000:5000
    environment:
      - POSTGRES_PASSWORD=${PGPASSWORD}
    networks:
      - governetwork
    depends_on:
      - "postgres"
networks:
  governetwork:
    driver: bridge