apiVersion: apps/v1
kind: Deployment
metadata:
  name: governetcore-backend
  labels:
    app: governetcore-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: governetcore-backend
  template:
    metadata:
      labels:
        app: governetcore-backend
    spec:
      containers:
      - name: governetcore-backend
        image: gcr.io/governet/governetcore_backend
        ports:
        - containerPort: 5000
