FROM node:8.15.0-stretch

WORKDIR /usr/src/governet

COPY package.json .
COPY package-lock.json .
RUN npm install

COPY serve.js .

ENV PGUSER=postgres
ENV PGHOST=postgres
ENV PGPASSWORD=example
ENV PGDATABASE=governet
ENV PGPORT=5432 

EXPOSE 8080

CMD ["node", "serve.js"]