CREATE TABLE candidates(
    CAND_ID VARCHAR (60) NOT NULL,
    CAND_NAME VARCHAR (60) NOT NULL,
    CAND_PTY_AFFILIATION VARCHAR (3) NOT NULL,
    CAND_ELECTION_YR VARCHAR (10) NOT NULL,
    CAND_OFFICE_ST VARCHAR (120) NOT NULL,
    CAND_OFFICE VARCHAR (60) NOT NULL,
    CAND_OFFICE_DISTRICT VARCHAR (60) NOT NULL,
    CAND_ICI VARCHAR (60) NOT NULL, 
    CAND_STATUS VARCHAR (60) NOT NULL,
    CAND_PCC VARCHAR (60) NOT NULL ,
    CAND_ST1 VARCHAR (60) NOT NULL,
    CAND_ST2 VARCHAR (60) NOT NULL,
    CAND_CITY VARCHAR (60) NOT NULL,
    CAND_ST VARCHAR (60) NOT NULL,
    CAND_ZIP VARCHAR (10) NOT NULL
);