CREATE TABLE candidates(
    CAND_ID VARCHAR (60) NOT NULL,
    CAND_NAME VARCHAR (60) NOT NULL,
    CAND_PTY_AFFILIATION VARCHAR (3) NOT NULL,
    CAND_ELECTION_YR VARCHAR (10) NOT NULL,
    CAND_OFFICE_ST VARCHAR (120) NOT NULL,
    CAND_OFFICE VARCHAR (60) NOT NULL,
    CAND_OFFICE_DISTRICT VARCHAR (60) NOT NULL,
    CAND_ICI VARCHAR (60) NOT NULL,
    CAND_STATUS VARCHAR (60) NOT NULL,
    CAND_PCC VARCHAR (60) NOT NULL ,
    CAND_ST1 VARCHAR (60) NOT NULL,
    CAND_ST2 VARCHAR (60) NOT NULL,
    CAND_CITY VARCHAR (60) NOT NULL,
    CAND_ST VARCHAR (60) NOT NULL,
    CAND_ZIP VARCHAR (10) NOT NULL
);

CREATE TABLE committees(
    CMTE_ID VARCHAR (60) NOT NULL,
    CMTE_NM VARCHAR (600) NOT NULL,
    TRES_NM VARCHAR (60) NOT NULL,
    CMTE_ST1 VARCHAR (60) NOT NULL,
    CMTE_ST2 VARCHAR (60) NOT NULL,
    CMTE_CITY VARCHAR (60) NOT NULL,
    CMTE_ST VARCHAR (60) NOT NULL,
    CMTE_ZIP VARCHAR (60) NOT NULL,
    CMTE_DSGN VARCHAR (60) NOT NULL,
    CMTE_TP VARCHAR (60) NOT NULL,
    CMTE_PTY_AFFILIATION VARCHAR (60) NOT NULL,
    CMTE_FILING_FREQ VARCHAR (60) NOT NULL,
    ORG_TP VARCHAR (60) NOT NULL,
    CONNECTED_ORG_NM VARCHAR (600) NOT NULL,
    CAND_ID VARCHAR (60) NOT NULL
);

CREATE TABLE cmte_contributions(
    CMTE_ID VARCHAR (60) NOT NULL,
    AMNDT_IND VARCHAR (60) NOT NULL,
    RPT_TP VARCHAR (60) NOT NULL,
    TRANSACTION_PGI VARCHAR (60) NOT NULL,
    IMAGE_NUM VARCHAR (60) NOT NULL,
    TRANSACTION_TP VARCHAR (60) NOT NULL,
    ENTITY_TP VARCHAR (60) NOT NULL,
    NAME VARCHAR (600) NOT NULL,
    CITY VARCHAR (60) NOT NULL,
    STATE VARCHAR (60) NOT NULL,
    ZIP_CODE VARCHAR (60) NOT NULL,
    EMPLOYER VARCHAR (600) NOT NULL,
    OCCUPATION VARCHAR (600) NOT NULL,
    TRANSACTION_DT VARCHAR (60) NOT NULL,
    TRANSACTION_AMT VARCHAR (60) NOT NULL,
    OTHER_ID VARCHAR (60) NOT NULL,
    CAND_ID VARCHAR (60) NOT NULL,
    TRAN_ID VARCHAR (60) NOT NULL,
    FILE_NUM VARCHAR (60) NOT NULL,
    MEMO_CD VARCHAR (60) NOT NULL,
    MEMO_TEXT VARCHAR (600) NOT NULL,
    SUB_ID VARCHAR (60) NOT NULL
);

